/**
 * Autogenerated by Thrift Compiler (0.18.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef GraphService_H
#define GraphService_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include <memory>
#include "graph_types.h"

namespace graph_rpc {

#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class GraphServiceIf {
 public:
  virtual ~GraphServiceIf() {}
  virtual void sendQueryBatch(std::vector<int32_t> & _return, const std::string& clientName, const std::vector<Query> & queryBatch) = 0;
};

class GraphServiceIfFactory {
 public:
  typedef GraphServiceIf Handler;

  virtual ~GraphServiceIfFactory() {}

  virtual GraphServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(GraphServiceIf* /* handler */) = 0;
  };

class GraphServiceIfSingletonFactory : virtual public GraphServiceIfFactory {
 public:
  GraphServiceIfSingletonFactory(const ::std::shared_ptr<GraphServiceIf>& iface) : iface_(iface) {}
  virtual ~GraphServiceIfSingletonFactory() {}

  virtual GraphServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) override {
    return iface_.get();
  }
  virtual void releaseHandler(GraphServiceIf* /* handler */) override {}

 protected:
  ::std::shared_ptr<GraphServiceIf> iface_;
};

class GraphServiceNull : virtual public GraphServiceIf {
 public:
  virtual ~GraphServiceNull() {}
  void sendQueryBatch(std::vector<int32_t> & /* _return */, const std::string& /* clientName */, const std::vector<Query> & /* queryBatch */) override {
    return;
  }
};

typedef struct _GraphService_sendQueryBatch_args__isset {
  _GraphService_sendQueryBatch_args__isset() : clientName(false), queryBatch(false) {}
  bool clientName :1;
  bool queryBatch :1;
} _GraphService_sendQueryBatch_args__isset;

class GraphService_sendQueryBatch_args {
 public:

  GraphService_sendQueryBatch_args(const GraphService_sendQueryBatch_args&);
  GraphService_sendQueryBatch_args& operator=(const GraphService_sendQueryBatch_args&);
  GraphService_sendQueryBatch_args() noexcept
                                   : clientName() {
  }

  virtual ~GraphService_sendQueryBatch_args() noexcept;
  std::string clientName;
  std::vector<Query>  queryBatch;

  _GraphService_sendQueryBatch_args__isset __isset;

  void __set_clientName(const std::string& val);

  void __set_queryBatch(const std::vector<Query> & val);

  bool operator == (const GraphService_sendQueryBatch_args & rhs) const
  {
    if (!(clientName == rhs.clientName))
      return false;
    if (!(queryBatch == rhs.queryBatch))
      return false;
    return true;
  }
  bool operator != (const GraphService_sendQueryBatch_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const GraphService_sendQueryBatch_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class GraphService_sendQueryBatch_pargs {
 public:


  virtual ~GraphService_sendQueryBatch_pargs() noexcept;
  const std::string* clientName;
  const std::vector<Query> * queryBatch;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _GraphService_sendQueryBatch_result__isset {
  _GraphService_sendQueryBatch_result__isset() : success(false) {}
  bool success :1;
} _GraphService_sendQueryBatch_result__isset;

class GraphService_sendQueryBatch_result {
 public:

  GraphService_sendQueryBatch_result(const GraphService_sendQueryBatch_result&);
  GraphService_sendQueryBatch_result& operator=(const GraphService_sendQueryBatch_result&);
  GraphService_sendQueryBatch_result() noexcept {
  }

  virtual ~GraphService_sendQueryBatch_result() noexcept;
  std::vector<int32_t>  success;

  _GraphService_sendQueryBatch_result__isset __isset;

  void __set_success(const std::vector<int32_t> & val);

  bool operator == (const GraphService_sendQueryBatch_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const GraphService_sendQueryBatch_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const GraphService_sendQueryBatch_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _GraphService_sendQueryBatch_presult__isset {
  _GraphService_sendQueryBatch_presult__isset() : success(false) {}
  bool success :1;
} _GraphService_sendQueryBatch_presult__isset;

class GraphService_sendQueryBatch_presult {
 public:


  virtual ~GraphService_sendQueryBatch_presult() noexcept;
  std::vector<int32_t> * success;

  _GraphService_sendQueryBatch_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class GraphServiceClient : virtual public GraphServiceIf {
 public:
  GraphServiceClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  GraphServiceClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void sendQueryBatch(std::vector<int32_t> & _return, const std::string& clientName, const std::vector<Query> & queryBatch) override;
  void send_sendQueryBatch(const std::string& clientName, const std::vector<Query> & queryBatch);
  void recv_sendQueryBatch(std::vector<int32_t> & _return);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class GraphServiceProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::std::shared_ptr<GraphServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext) override;
 private:
  typedef  void (GraphServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_sendQueryBatch(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  GraphServiceProcessor(::std::shared_ptr<GraphServiceIf> iface) :
    iface_(iface) {
    processMap_["sendQueryBatch"] = &GraphServiceProcessor::process_sendQueryBatch;
  }

  virtual ~GraphServiceProcessor() {}
};

class GraphServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  GraphServiceProcessorFactory(const ::std::shared_ptr< GraphServiceIfFactory >& handlerFactory) noexcept :
      handlerFactory_(handlerFactory) {}

  ::std::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo) override;

 protected:
  ::std::shared_ptr< GraphServiceIfFactory > handlerFactory_;
};

class GraphServiceMultiface : virtual public GraphServiceIf {
 public:
  GraphServiceMultiface(std::vector<std::shared_ptr<GraphServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~GraphServiceMultiface() {}
 protected:
  std::vector<std::shared_ptr<GraphServiceIf> > ifaces_;
  GraphServiceMultiface() {}
  void add(::std::shared_ptr<GraphServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void sendQueryBatch(std::vector<int32_t> & _return, const std::string& clientName, const std::vector<Query> & queryBatch) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->sendQueryBatch(_return, clientName, queryBatch);
    }
    ifaces_[i]->sendQueryBatch(_return, clientName, queryBatch);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class GraphServiceConcurrentClient : virtual public GraphServiceIf {
 public:
  GraphServiceConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot, std::shared_ptr< ::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(prot);
  }
  GraphServiceConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot, std::shared_ptr< ::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void sendQueryBatch(std::vector<int32_t> & _return, const std::string& clientName, const std::vector<Query> & queryBatch) override;
  int32_t send_sendQueryBatch(const std::string& clientName, const std::vector<Query> & queryBatch);
  void recv_sendQueryBatch(std::vector<int32_t> & _return, const int32_t seqid);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  std::shared_ptr< ::apache::thrift::async::TConcurrentClientSyncInfo> sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif

} // namespace

#endif
