// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "GraphService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using namespace  ::graph_rpc;

class GraphServiceHandler : virtual public GraphServiceIf {
 public:
  GraphServiceHandler() {
    // Your initialization goes here
  }

  void sendQueryBatch(std::vector<int32_t> & _return, const std::string& clientName, const std::vector<Query> & queryBatch) {
    // Your implementation goes here
    printf("sendQueryBatch\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  ::std::shared_ptr<GraphServiceHandler> handler(new GraphServiceHandler());
  ::std::shared_ptr<TProcessor> processor(new GraphServiceProcessor(handler));
  ::std::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::std::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::std::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

